#version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: symfony_app
        volumes:
            - '.:/app'
        depends_on:
            - database
            - database_test

    nginx:
        image: nginx:latest
        container_name: symfony_nginx
        ports:
            - "8888:80"
        volumes:
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - '.:/app'
        depends_on:
            - app

    database:
        image: mysql:latest
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "!ChangeMe!"
            MYSQL_PASSWORD: "!ChangeMe!"
            MYSQL_USER: app
            MYSQL_DATABASE: app
        ports:
            - "${DATABASE_PORT:-3307}:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    database_test:
        image: mysql:latest
        container_name: mysql_db_test
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "!ChangeMe!"
            MYSQL_PASSWORD: "!ChangeMe!"
            MYSQL_USER: app
            MYSQL_DATABASE: app_test
        ports:
            - "${DATABASE_TEST_PORT:-3308}:3306"
        volumes:
            - mysql_test_data:/var/lib/mysql

volumes:
    mysql_data:
    mysql_test_data:
